Alfresco/activiti-android-app

activiti-app/src/main/res/values/strings.xml
activiti-app/src/main/res/values/strings_activity_login.xml

Rebranding

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/DateTimeField.java

Story https://issues.alfresco.com/jira/browse/ANDROID-600

ANDROID-600 Inconsistency on date and time format

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/DateTimeField.java
activiti-app/src/main/java/com/activiti/android/ui/utils/TimeUtils.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-601

ANDROID-601 Date time custom format does not display selected values for day and year

---

activiti-app/build.gradle
activiti-app/src/main/java/com/activiti/android/app/fragments/settings/GeneralSettingsFragment.java
build.gradle

JIRA https://issues.alfresco.com/jira/browse/ANDROID-603

ANDROID-603 Crash on tap "Third party notice"

---

activiti-app/src/main/java/com/activiti/android/app/fragments/account/AccountEditFragment.java
activiti-app/src/main/java/com/activiti/android/app/fragments/settings/AccountSettingsFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-608

ANDROID-608 Settings button inactive after tap on Confirm on Edit user and server info

---

activiti-app/src/main/java/com/activiti/android/app/fragments/user/UserProfileFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-607

ANDROID-607 Burger menu inactive from Profile page

---

activiti-app/src/main/java/com/activiti/android/ui/fragments/content/ContentsFoundationFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-609

ANDROID-609 Not able to add content to a process instance from See all page

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/DropDownField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/HyperlinkField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/UploadPickerField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/UserGroupPickerField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/UserPickerField.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-621

ANDROID-621 Crash on attempt to complete user task 2 from outside

---

activiti-app/src/main/res/values/strings_libs.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-700

ANDROID-700 On APS we still have "Copyright (C) 2005-2015"

---

activiti-app/build.gradle
activiti-app/src/main/java/com/activiti/android/ui/fragments/task/form/SaveFormWorker.java
activiti-app/src/main/java/com/activiti/android/ui/fragments/task/form/TaskFormFoundationFragment.java
activiti-app/src/main/java/com/activiti/android/ui/utils/WorkerManagerUtils.java
activiti-app/src/main/res/values/strings.xml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

JIRA https://issues.alfresco.com/jira/browse/ANDROID-728

ANDROID-728 Offline working in APS - Forms

---

activiti-app/build.gradle

The error is: groovy.lang.GroovyRuntimeException: Cannot set the value of read-only property 'outputFile'

Fixed bamboo error when trying to build the project.

---

activiti-app/build.gradle
activiti-app/src/main/java/com/activiti/android/ui/form/fields/ReadOnlyTextField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/TypeAhead.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-770

ANDROID-770 Alfresco Process Services App crashes on Show Form

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/HyperlinkField.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-796

[APS] Application is crashing when tapping on hyperlink on forms

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/HyperlinkField.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-797
also this fixes https://issues.alfresco.com/jira/browse/ANDROID-796

[APS] Application is crashing when tapping forms with hyperlinks

---

activiti-app/src/main/java/com/activiti/android/ui/form/FieldTypeFactory.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-793

[APS] Application is crashing when showing specific forms

---

activiti-app/src/main/AndroidManifest.xml
activiti-app/src/main/java/com/activiti/android/app/fragments/task/TaskFormFragment.java
activiti-app/src/main/java/com/activiti/android/ui/utils/IntentUtils.java
activiti-app/src/main/res/xml/provider_paths.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-798

[APS] Application is crashing when trying to view content attached in form

---

activiti-app/src/main/java/com/activiti/android/ui/fragments/base/BasePagingGridFragment.java
activiti-app/src/main/java/com/activiti/android/ui/fragments/process/ProcessDetailsFoundationFragment.java
activiti-app/src/main/java/com/activiti/android/ui/fragments/task/form/TaskFormFoundationFragment.java
activiti-app/src/main/java/com/activiti/android/ui/fragments/user/UserProfileFoundationFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-792

[APS] Application is crashing when switching the connection to internet that has no access to server

---

activiti-app/src/main/java/com/activiti/android/app/fragments/process/ProcessesFragment.java
activiti-app/src/main/java/com/activiti/android/ui/fragments/form/picker/IdmPickerFragment.java
activiti-app/src/main/java/com/activiti/android/ui/fragments/task/TaskDetailsFoundationFragment.java
activiti-app/src/main/java/com/activiti/android/ui/utils/UIUtils.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-794

[APS] Application is crashing when trying to assign the task to a person

---

activiti-app/src/main/java/com/activiti/android/ui/form/FormManager.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/TabField.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-799

[APS] Application is crashing when selecting different radio buttons on specific form

---

activiti-app/src/main/java/com/activiti/android/ui/fragments/task/form/SaveFormWorker.java
activiti-app/src/main/java/com/activiti/android/ui/fragments/task/form/TaskFormFoundationFragment.java
activiti-app/src/main/java/com/activiti/android/ui/utils/WorkerManagerUtils.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-801

[APS] Application is crashing when saving specific form in Offline mode.

---

activiti-app/src/main/java/com/activiti/android/ui/fragments/process/create/StartSimpleFormDialogFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-802

[APS] The application is crashing when tapping multiple times on create process

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/TypeAhead.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-814

[APS] Typeahead field doesn't show the results

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/TypeAhead.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-815

App crashes when trying to see the chosen item from the typeahead field

---

activiti-app/src/main/java/com/activiti/android/ui/form/FormManager.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/TabField.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-816

[APS] Tab visibility condition doesn't work properly

---

activiti-app/src/main/java/com/activiti/android/ui/form/FormManager.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/BaseField.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-817
this also fixes https://issues.alfresco.com/jira/browse/ANDROID-818

[APS] Section visibility condition doesn't work

---

activiti-app/src/main/java/com/activiti/android/ui/form/FormManager.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/AmountField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/BaseField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/CheckBoxField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/DateField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/DateTimeField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/DropDownField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/DynamicTableField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/HeaderField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/HyperlinkField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/MultiLineTextField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/RadioButtonsField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/TextField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/TypeAhead.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/UploadPickerField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/UserGroupPickerField.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/UserPickerField.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-820
also fixes https://issues.alfresco.com/jira/browse/ANDROID-822

[APS] The application is crashing when switching the rotation while viewing a form

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/TypeAhead.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-833

[APS] Type-ahead changes its value when switching the rotation of the device

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/HyperlinkField.java
activiti-app/src/main/res/layout/form_hyperlink.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-835

ANDROID-835 - [APS] The application is crashing when switching the rotation while viewing a specific form

---

activiti-app/src/main/java/com/activiti/android/ui/fragments/common/AbstractDetailsFragment.java
activiti-app/src/main/java/com/activiti/android/ui/fragments/process/ProcessDetailsFoundationFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-776

ANDROID-776 [APS] Application is crashing when loading processes in specific states

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/TypeAhead.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-838

ANDROID-838 [APS] Different format for the dislay typeahead fields

---

activiti-app/src/main/java/com/activiti/android/ui/form/FormManager.java
activiti-app/src/main/java/com/activiti/android/ui/form/fields/TypeAhead.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-839

ANDROID-839 [APS] Label should be displayed in display value of id-typeahead

---

activiti-app/src/main/java/com/activiti/android/ui/form/FormManager.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-840

ANDROID-840 [APS] Application crashes when showing specific forms

---

activiti-app/src/main/java/com/activiti/android/ui/fragments/process/ProcessDetailsFoundationFragment.java
activiti-app/src/main/res/layout/fr_process_details.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-846

ANDROID-846 [APS] Start form title appears when there's no start form

---

activiti-app/src/main/java/com/activiti/android/ui/form/fields/DropDownField.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-845

[APS] Drop down has no options

---

activiti-app/build.gradle
activiti-app/src/main/java/com/activiti/android/app/fragments/task/startform/StartFormFragment.java
activiti-app/src/main/java/com/activiti/android/ui/fragments/task/form/TaskFormFoundationFragment.java
gradle.properties

JIRA https://issues.alfresco.com/jira/browse/ANDROID-857

[APS] Endless spin displayed when showing a form attached to a task

---

activiti-app/src/main/java/com/activiti/android/app/fragments/account/SignInFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-858

[APS] Account - Application is crashing if the address to connect to contains spaces

---

activiti-app/build.gradle
gradle.properties

JIRA https://issues.alfresco.com/jira/browse/ANDROID-860

ANDROID-860 Update APS Android Target
